other test

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -8,22 +8,13 @@ github-sync:
     - apk update && apk add git openssh
     
   script:
-    # Configure git
     - git config --global user.name "${GITLAB_USER_NAME}"
     - git config --global user.email "${GITLAB_USER_EMAIL}"
-    
-    # Prepare branch
     - git checkout ${CI_COMMIT_SHA}
     - git checkout -b public
-    
-    # Setup and push to GitHub
     - git remote remove github || true
-    - git remote add github "https://${GITHUB_TOKEN}@github.com/kowiste-iot/web.git"
-    - |
-      if ! git push -u github public:main --force; then
-        echo "Failed to push to GitHub"
-        exit 1
-      fi
+    - 'git remote add github "https://oauth2:${GITHUB_TOKEN}@github.com/kowiste-iot/web.git"'
+    - git push -u github public:main --force || (echo "Failed to push to GitHub" && exit 1)
   
   rules:
     - if: '$CI_COMMIT_BRANCH == "public"'
